### ISSUE TITLE
Data table show additional info

### ISSUE THREAD

**Issue by amarkensteijn** [Deltares/fews-web-oc#172]
Show flag and comments in data table

**Comment by amarkensteijn** [comment]
Requires https://github.com/Deltares/fews-pi-requests/pull/98

**Comment by ekkelenkamp** [comment]
@amarkensteijn , i fixed the tests by refactoring the call to require.context into a seperate function. This allows running the unit tests by mocking that function.
I had to fix the unit test itsef as well. I think the data format was changed. Can you review please?
