### ISSUE TITLE
Update the chart legend and title when a coord is selected

### ISSUE THREAD

**Issue by hvangeffen** [Deltares/fews-web-oc#240]

**Comment by hvangeffen** [comment]
Backend title is used now and current title is set in `timeseriesdisplay.ts`.
In that file we could hardcode the title to be changed to something showing the used coordinates, but shouldn't this be set in the backend to a desired title value?

**Comment by vanmeeuwen** [comment]
Actually the request is an elevation request. The correct axis is set in the xaxis response. We need to have a separate elevationseriesdisplay probably
