### ISSUE TITLE
Add mindef and navy logo's

### ISSUE THREAD

**Issue by vanmeeuwen** [Deltares/fews-web-oc#331]

**Comment by vanmeeuwen** [comment]
[Logos.docx](https://github.com/Deltares/fews-web-oc/files/12925496/Logos.docx)
only logo's without text  United Arab Emirates Min. of Def. is needed

**Comment by hvangeffen** [comment]
Can these be placed anywhere?

**Comment by vanmeeuwen** [comment]
> Where on the page should these be displayed?

- At browser window icon: the top one (Navy)
- At top of the sidebar, below the Deltares text: Navy, rechts van Deltares: Mindef logo
Not inside the same Deltares area though, but in the sidebar area
If it would look better, then it may be put at the bottom of the sidebar
