### ISSUE TITLE
Direct route to a location doesn't show it on the map

### ISSUE THREAD

**Issue by vanmeeuwen** [Deltares/fews-web-oc#631]
Go to for instance: http://localhost:5173/topology/node/oceanographic_waves_swan/map/oceanographic_waves_swan/location/obs162

The console shows:
Uncaught (in promise) DOMException: The operation was aborted. 
    useTimeSeries index.ts:68
    callWithErrorHandling runtime-core.esm-bundler.js:158
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    getter runtime-core.esm-bundler.js:1709
    run reactivity.esm-bundler.js:178

The selected location is not highlighted

**Comment by wkramer** [comment]
Is not due to error. That is related to aborting time series requests when new time series are loaded. That is in issue in useTimeSeries triggering twice on initial load.
