### ISSUE TITLE
Reenable zoom handler

### ISSUE THREAD

**Issue by wkramer** [Deltares/fews-web-oc#743]
The zoom handler in fews-web-oc-charts uses Node events, this should be resolved.
This gives an issue with Maplibre.
The zoom handler is currently disabled.
When the fews-web-oc-charts is fixed we should:

- [ ] Reenable zoomhandler
- [ ] Remove "vite-plugin-node-polyfills": "^0.21.0" dependency

**Comment by hvangeffen** [comment]
Charts PR: https://github.com/Deltares/fews-web-oc-charts/pull/85
